name: build-on-command

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[build]') || github.event_name == 'workflow_dispatch'"

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: temurin
    - name: Build with Gradle
      run: ./gradlew jar
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/libs
